site_name: G.algos
site_url: https://g-algos.com

theme:
  name: material
  palette:
    primary: deep purple
    accent: yellow
  font:
    text: Comfortaa
  favicon: assets/GA.png
  logo: assets/Galgo_32.svg
  custom_dir: overrides
  icon:
    logo: Galgo_32.svg

plugins:
  - search
  - meta
  - social:
      cards_layout: default/variant
      cards_layout_options:
        background_image: layouts/background_normal.png
        background_color: transparent
      cards_layout_dir: layouts

watch:
  - layouts
